/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework_8_Question_13_reverseThread */

#ifndef _Included_Homework_8_Question_13_reverseThread
#define _Included_Homework_8_Question_13_reverseThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework_8_Question_13_reverseThread
 * Method:    setJNIEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Homework_18_Question_113_reverseThread_setJNIEnv
  (JNIEnv *, jclass);

/*
 * Class:     Homework_8_Question_13_reverseThread
 * Method:    reversefunc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Homework_18_Question_113_reverseThread_reversefunc
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
