/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework_8_Question_11_passStringFromC_reverse */

#ifndef _Included_Homework_8_Question_11_passStringFromC_reverse
#define _Included_Homework_8_Question_11_passStringFromC_reverse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework_8_Question_11_passStringFromC_reverse
 * Method:    reversefunc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Homework_18_Question_111_passStringFromC_reverse_reversefunc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
