/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework_8_Question_11_passStringsFromC_daysofweek */

#ifndef _Included_Homework_8_Question_11_passStringsFromC_daysofweek
#define _Included_Homework_8_Question_11_passStringsFromC_daysofweek
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework_8_Question_11_passStringsFromC_daysofweek
 * Method:    returndays
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Homework_18_Question_111_passStringsFromC_daysofweek_returndays
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
