/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework_8_Question_11_HelloWorld */

#ifndef _Included_Homework_8_Question_11_HelloWorld
#define _Included_Homework_8_Question_11_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework_8_Question_11_HelloWorld
 * Method:    cfunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Homework_18_Question_111_HelloWorld_cfunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
