/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework_8_Question_11_parseIntegerFromC_factorial */

#ifndef _Included_Homework_8_Question_11_parseIntegerFromC_factorial
#define _Included_Homework_8_Question_11_parseIntegerFromC_factorial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework_8_Question_11_parseIntegerFromC_factorial
 * Method:    fact
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Homework_18_Question_111_parseIntegerFromC_factorial_fact
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
