/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework_8_Question_11_passArraysFromC_fibo */

#ifndef _Included_Homework_8_Question_11_passArraysFromC_fibo
#define _Included_Homework_8_Question_11_passArraysFromC_fibo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework_8_Question_11_passArraysFromC_fibo
 * Method:    returnfibo
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Homework_18_Question_111_passArraysFromC_fibo_returnfibo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
